EmployeeManagementSystem/urls.py
from itertools import pairwise
from unicodedata import name
from django.contrib import admin
from django.urls import path
from employee.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index , name='index'),
    path('login/' ,admin_login , name = 'adminLogin'),
    path('adminLogout/', admin_logout , name='adminLogout'),
    path('login/addemployee/',add_employee,name='addEmployee'),
    path('delete/<int:id>/', delete_emp, name='delete'),
    path('updateemp/<int:id>/',update_emp,name='update'),
    path('login/addadmin/',add_admin,name='addAdmin'),
    path('showemp/',show_employee,name='showemp'),
    path('showadm/',show_admin,name='showadm'),
    path('updateadm/<int:id>/',update_adm,name='updateadm'),
    path('deleteadm/<int:id>/',delete_adm,name='deleteadm'),
    path('emp_csv/',show_emp_csv,name='emp_csv'),
    path('adm_csv/',show_adm_csv,name='adm_csv'),
    path('ajax/load-states/',load_states,name='ajax_load_states'),
    path('ajax/load-cities/',load_cities,name='ajax_load_cities'),
    # path('change-password/<token>',change_password,name='change_password'),
    # path('forget-password/',forget_password,name='forget-password'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

employee/models.py
from django.contrib.auth.models import AbstractBaseUser ,BaseUserManager , UserManager
from django.db import models
from django.contrib.auth.models import PermissionsMixin




# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Gender(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

class Employee(models.Model):
    first_name = models.CharField (max_length=50)
    last_name = models.CharField (max_length=50)
    gender = models.ForeignKey(Gender,on_delete=models.SET_NULL, null=True)
    email = models.CharField (max_length=50)
    resume = models.FileField(null=True)
    address = models.CharField (max_length=50)
    country = models.ForeignKey(Country ,on_delete=models.SET_NULL , null=True)
    state = models.ForeignKey(State ,on_delete=models.SET_NULL , null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL , null=True)
    pincode = models.IntegerField()
    created_at=models.DateField(null=True)
    updated_at=models.DateField(null=True)
    is_deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.first_name 
    
    

class Role(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
         
class MyUserManager(BaseUserManager):
    def create_user(self,role, email, date_of_birth, password=None):
        
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
            role=role
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,role, email,date_of_birth,password=None,):
       
        user = self.create_user(email,password=password,date_of_birth=date_of_birth,role=role)
        user.is_admin = True
        user.save(using=self._db)
        return user


class Admin(AbstractBaseUser,PermissionsMixin):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField( max_length=50)
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
    # date_of_birth = models.DateField()
    created_at=models.DateField(auto_now_add=True,blank=True,null=True)
    updated_at=models.DateTimeField(auto_now=True,blank=True,null=True)
    role = models.ForeignKey(Role,on_delete=models.DO_NOTHING,default=None,null=True)
    is_deleted =  models.BooleanField(default=0)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
       return True

    @property
    def is_staff(self):
       return self.is_admin




class Profile(models.Model):
    user = models.OneToOneField(Admin,on_delete=models.CASCADE)
    forget_password_token = models.CharField( max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email
    

    




    
    

employee/views.py
from email import message
import email
from logging import lastResort
from urllib import response
from django.shortcuts import render
from .models import *
from django.contrib.auth import logout , authenticate , login 
from django.shortcuts import render ,HttpResponseRedirect,redirect,HttpResponse
from .forms import AdminAdd, EmployeeAdd, Employeeupdate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
import csv


# Create your views here.


def index(request):
    return render(request , 'index.html')



def admin_login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        
        user = authenticate(request,email=email,password=password)
        print (user is not None)
        if user is not None:
            login(request,user)
            
            return render(request,'welcome.html')
        
        else:
            messages.warning(request,"Credentials do not match. Please check your email or password")
           
        
    else:
         return render(request,'admin_login.html')
    
    return render(request,'admin_login.html')




def admin_logout(request):
    
    logout(request)
    




@login_required(login_url='/login')
def add_employee(request):
    employee = Employee.objects.all()
    form = EmployeeAdd()
    if request.method=='POST':
        form = EmployeeAdd(request.POST,request.FILES)
        for emp in employee:
            if emp.email == form.data.get('email'):
                messages.warning(request, 'email already exists.')
            elif form.is_valid():
                form.save()
                messages.success(request,"Employee added successfully")
                form=EmployeeAdd()
        
            else:
                form=EmployeeAdd()
    return render(request,'add_employee.html',{'form':form})





def update_emp(request,id):
    country = Country.objects.all()
    
    if request.method =='POST':
        pi = Employee.objects.get(pk=id)
        form = Employeeupdate(request.POST , instance=pi)
        if form.is_valid():
            form.save()
            messages.success(request,"Employee updated successfully")
    else:
        pi = Employee.objects.get(pk=id)
        form = Employeeupdate(instance=pi) 
        
    return render(request,'edit_employees.html',{'country':country,'form':form,'edit':pi})





def delete_emp(request,id):
    if request.method == 'POST':
        pi = Employee.objects.get(pk=id)
        pi.delete()
        messages.success(request,"Employee deleted successfully")
        return redirect('showemp') 





def show_employee(request):   
    show=Employee.objects.all()
    p = Paginator(Employee.objects.all(),2)
    page = request.GET.get('page')
    Emp = p.get_page(page)
    return render(request,'show_emp.html',{'Emp':Emp})





def add_admin(request):
    form = AdminAdd()
    if request.method=='POST':
        form = AdminAdd(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Admin added successfully")
            form=AdminAdd()
        
        else:
            form=AdminAdd() 
    return render(request,'add_admin.html',{'form':form})






def update_adm(request,id):
    if request.method == 'POST':
        pi = Admin.objects.get(pk=id)
        form = AdminAdd(request.POST,instance=pi)
        form.is_valid()
        form.save()
        messages.success(request,"Admin updtaed successfully")
    else:
        pi = Admin.objects.get(pk=id)
        form = AdminAdd(instance=pi)
    return render (request ,'edit_admin.html',{'form':form})




def delete_adm(request,id):
    if request.method == 'POST':
        pi = Admin.objects.get(pk=id)
        pi.delete()
        messages.success(request,"Admin deleted successfully")
        return redirect('showadm')




def show_admin(request):
    show=Admin.objects.all()
    p = Paginator(Admin.objects.all(),2)
    page = request.GET.get('page')
    Adm = p.get_page(page)
    # return render(request,'add_employee.html',{'form':form,'stu':show})
    return render(request,'show_admin.html',{'Adm':Adm})






def show_emp_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename = Employees.csv'

    writer = csv.writer(response)
    show=Employee.objects.all()

    writer.writerow(['FirstName','LastName','Gender','Email','Address','Country','State','City','Pincode'])

    for emp in show:
        writer.writerow([emp.first_name,emp.last_name,emp.gender,emp.email,emp.address,emp.country,emp.state,emp.city,emp.pincode])
    
    return response




def show_adm_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename = Admin.csv'

    writer = csv.writer(response)
    show=Admin.objects.all()

    writer.writerow(['FirstName','LastName','Email','Role'])

    for adm in show:
        writer.writerow([adm.first_name,adm.last_name,adm.email,adm.role])
    
    return response
 
def country(request):
    country = Country.objects,all()
    d={'country':country}
    return render(request,'add_employee.html',d)

def load_states(request):
    country_id=request.GET.get('country_id')
    states = State.objects.filter(country_id=country_id).order_by('name')
    return render(request,'states.html',{'states':states})


def load_cities(request):
    state_id=request.GET.get('state_id')
    cities = City.objects.filter(state_id=state_id).order_by('name')
    return render(request,'cities.html',{'cities':cities})







# from .helpers import send_forget_password_mail
# import uuid



# def change_password(request , token):
#     context = {}
    
    
#     try:
#         profile_obj = Profile.objects.filter(forget_password_token = token).first()
#         context = {'email' : profile_obj}
        
#         if request.method == 'POST':
#             new_password = request.POST.get('new_password')
#             confirm_password = request.POST.get('reconfirm_password')
#             email = request.POST.get('email')
            
#             if email is  None:
#                 messages.success(request, 'No email found.')
#                 return redirect(f'/change-password/{token}/')
                
            
#             if  new_password != confirm_password:
#                 messages.success(request, 'both should  be equal.')
#                 return redirect(f'/change-password/{token}/')
                         
            
#             user_obj = Admin.objects.get(id = email)
#             user_obj.set_password(new_password)
#             user_obj.save()
#             return redirect('/login/')
            
            
            
        
        
#     except Exception as e:
#         print(e)
#     return render(request , 'change-password.html' , context)


# def forget_password(request):
#     try:
#         if request.method == 'POST':
#             email = request.POST.get('email')
            
#             if not Admin.objects.filter(email=email).first():
#                 messages.success(request, 'Not user found with this email.')
#                 return redirect('/forget-password/')
            
#             user_obj = Admin.objects.get(email = email)
#             token = str(uuid.uuid4())
#             # profile_obj= Profile.objects.get(user = user_obj)
#             # profile_obj.forget_password_token = token
#             # profile_obj.save()
#             send_forget_password_mail(user_obj.email , token)
#             messages.success(request, 'We have sent you a password recovery email')
#             return redirect('/forget-password/')
                
    
    
#     except Exception as e:
#         print(e)
#     return render(request , 'forget-password.html')




























# def change_password(request,token):
#     context={}
#     try:
#         profie_obj = Profile.objects.get(forget_password_token=token).first()
#         print (profie_obj)
#         context = {'user_id':profie_obj.user.id}


#     except Exception as e:
#         print (e)

#     return render(request,'change-password.html',context)


# def forget_password(request):
#     try:
#         if request.method == 'POST':
#             email = request.POST.get('email')

#             if not Admin.objects.filter(email=email).first():
#                 messages.success(request,"No user found with this email")
#                 return redirect('/forget-password/')

#             user_obj = Admin.objects.get(email=email)
#             token =str(uuid.uuid4()) 
#             profile_obj = Profile.objects.get(user=user_obj)
#             profile_obj.forget_password_token = token
#             profile_obj.save()
#             send_forget_password_mail(user_obj,token)
#             messages.success(request,"An email is sent")
#             return redirect('/forget-password/')

#     except Exception as e:
#         print (e)
#     return render(request,'forget-password.html')

employee/templates/add_admin.html
{% include 'header.html' %}
<head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body style="background-color: lightblue;">
    <div class="container">
        {% if messages %}
            
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
                {% endfor %}
            
        {% endif %}
    </div>
    <a href="{% url 'showadm' %}" ><button class="btn btn-dark m-3" style ="float: right;">Show Admin</button></a>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    <div class="container" style="margin-top:50px">
        <h2 class="text-center" style="border-bottom:2px solid black ;margin-left: 200px;margin-right: 200px;">Add Admin</h2>
        <br>
            <div  class="container"  style="margin-left:250px;margin-top: 50px;">
                <form action="" method="POST" class="m-3" id="Addadmin" name="Addadmin">
                        
                    {%csrf_token%}
                    {% for field in form%}

                    <label for="" class="form-label text-center">{{field.label}}</label>
                    {{field}}
                    <br>
                    
                    {% endfor %}
                    
                    <input type="submit" class="btn btn-primary m-5" value="Save">
                </form>
            </div>
                    
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<script>
$(document).ready(function() {
$("#Addadmin").validate({
rules: 
{
    firstname : {
    required: true
    },
    lastname: {
    required: true
    },
    email: {
    required: true,
    email: true
    },
   
    
},
message:{
    firstname:"Please Enter last name",
    lastname:"Please Enter last name",
    email:"Please Enter email",
    
}
});
});
</script>

        
</body>

employee/templates/add_employee.html
{% include 'header.html' %}
<head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body style="background-color: lightblue;">
        <div class="container">
            {% if messages %}
                
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
                    {% endfor %}
                
            {% endif %}
        </div>
        <a href="{% url 'showemp' %}" ><button class="btn btn-dark m-3" style ="float: right;">Show Employee</button></a>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<div class="container" style="margin-top:50px" >
    <div-col-sm-8 offset-2 class="m-3">
        <h2 class="text-center" style="border-bottom:2px solid black ;margin-left: 200px;margin-right: 200px;">Add Employee</h2>
        
        <div class="container"  style="margin-left:250px;margin-top: 50px;">
            <form action="" method="POST" id="Employee" enctype="multipart/form-data" data-states-url="{% url 'ajax_load_states'%}" data-cities-url="{% url 'ajax_load_cities'%}">
                {%csrf_token%}
                {{form.as_p}}
                <br><br>
                <input type="submit" class="btn btn-success" value="Save">
            </form>
        </div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function(){
        const url = $("#Employee").attr("data-states-url");
        const countryId = $(this).val();

        $.ajax({
            url:url,
            data:{
                'country_id':countryId
            },
            success: function(data){
                $("#id_state").html(data);
            }
        })
    })

    
</script>
<script>
    $("#id_state").change(function(){
        const url = $("#Employee").attr("data-cities-url");
        const stateId = $(this).val();

        $.ajax({
            url:url,
            data:{
                'state_id':stateId
            },
            success: function(data){
                $("#id_city").html(data);
            }
        })
    })

    
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>

<script>
$(document).ready(function() {
$("#Employee").validate({


});
});
</script>

employee/templates/admin_login.html
{% include 'header.html' %}
<div class="container">
    {% if messages %}
        
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
            {% endfor %}
        
    {% endif %}
</div>

    <div class = "card shadow m-5" style="background:grey">
        <div class = "card-body">
        
            <h3 class="text-center" style = "border-bottom : 4px solid rgb(22, 21, 21)"> Signin to your account</h3>

            <div class="container-fluid" style="margin-top: 50px;">
                <form  method="post" id="login">
                    {% csrf_token %}
                    <div class="form-row">
                    
                    

                        <div class="col-sm-6">
                            <div class="form-group m-2" >
                                <label><h5>Email</h5></label>
                                <input type="email" name="email" class="form-control" placeholder="Enter your Email"  required>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group m-2" >
                                <label><h5>Password</h5></label>
                                <input type="password" name="password" class="form-control" placeholder="Enter your Password"  required>
                            </div>
                        </div>
                        
                        
                        
                        
                        <div>
                            <input type="submit" value="Login" class="m-2 px-3 btn btn-success mt-4">
                           <br>
                            <button class="btn btn-dark" style="margin-left:10px ;"><a href="{% url 'password_reset'%}">Forget Password</a></button>
                        </div>
                        
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
    
    <script>
    $(document).ready(function() {
    $("#login").validate({
    
    
    });
    });
    </script>

employee/templates/change-password.html
{% include 'header.html' %}
{% block start %}
<body  style="background-color:lightblue ;">
    <div class="form-float">
        <div class="container">
            {% if messages %}
                
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
                    {% endfor %}
                
            {% endif %}
        </div>
    <div class="container" style="margin-top:50px ;">
        <form method="post" class="form" id="form">
            {% csrf_token %}
            <h3 style="text-align: center;border-bottom:2px solid black;margin-left: 250px;margin-right: 250px;">Change Password</h3>
           <br>
    
         
            <div class="form-group">
                <label for="password"><h5>Password</h5></label>
                <input type="password" name="new_password"  class="form-control" placeholder="Please enter your new password">
               
            </div>
    
    
    
            <div class="form-group">
                <label for="password"><h5>Confirm password</h5></label>
                <input type="text" name="reconfirm_password"   class="form-control" placeholder="Please confirm your new password">
               
            </div>
    
    
            <input type="hidden" name="email" value="{{email}}">
            
           <br>
            <button class="btn btn-success" type="submit">Submit</button>
    
        </form>
    </div>
</body>


{% endblock %}

employee/templates/cities.html
<option value="">------</option>
{% for city in cities%}
<option value="{{city.pk}}">{{city.name}}</option>
{% endfor %}

employee/templates/edit_admin.html
{% include 'header.html' %}
<head>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body style="background-color: lightblue;">
        <div class="container">
            {% if messages %}
                
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
                    {% endfor %}
                
            {% endif %}
        </div>
        <a href="{% url 'showadm' %}" class="btn btn-info m-2 " style="float: right;padding: auto;">Back to Admin</a>
    <div class="row m-3" >
        <div-col-sm-8 offset-2 class="m-3">
            <h2 class="text-center" style="border-bottom:2px solid black ;margin-left: 200px;margin-right: 200px;">Update Admin Information</h2>
           <div class="container"  style="margin-left:250px;margin-top: 50px;">
            <form action="" method="POST" id>
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit" class="btn btn-success" value="Update">
                
            </form>
        </div>
        </div>
    </div>
</body>

employee/templates/forget-password.html
{% include 'header.html'%}
{% block start %}
<body style="background-color:lightblue ;">
    <div class="form-float">
        <div class="container">
            {% if messages %}
                
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} m-2 " role="alert">{{ message }}</div>
                    {% endfor %}
                
            {% endif %}
        </div>
    <div class="container" style="background: lightblue;margin-top: 50px;">
        <form class="form" method="post" id="form">
            {% csrf_token %}
            <h3 style="text-align: center;border-bottom:2px solid black;margin-left: 250px;margin-right: 250px;">Forget Password</h3>
<br>
<h4 style="text-align: center;color: green;margin-left: 250px;margin-right: 250px;">We are here to help. <br>Please provide your registered email to continue</h4>
            
    

            <br>
         
            <div class="form-group">
                <label for="email"><h5>Email</h5></label>
                <input type="email" name="email"  class="form-control" placeholder="Please enter your email">
               
            </div>
    
            
           
            <button class="btn btn-primary" type="submit">Submit</button>
    
        </form>
    </div>
</body>


{% endblock %}

employee/templates/header.html
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="#">Employee Management System</a>
  
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration' %}">Employee registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employeeLogin'%}">Employee lo</a>
        </li> {% endcomment %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'adminLogin' %}">Admin login</a>
          </li>
          
      </ul>
    </div>
  </nav>

employee/templates/index.html
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="#">Employee Management System</a>
  
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'registration' %}">Employee registration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employeeLogin'%}">Employee lo</a>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'adminLogin' %}">Admin login</a>
          </li> {% endcomment %}
          
      </ul>
    </div>
  </nav>
<body style="background-color: aqua;">
    <div class="container" style="color:rgb(70, 68, 68);margin-top: 50px;background-color: rgb(194, 187, 187);">
        <h3 class="text-center" style="border-bottom: 2px solid black;">Welcome to Employeee Management System</h3>
        <h4 class="text-center" style="margin-top:20px ;border-bottom:2px solid black; margin:50px; margin-left:200px ;margin-right: 200px;">Please Signin to proceed</h4>

    </div>
    <div class="text-center">
        <button class="btn btn-dark"><a href="{% url 'adminLogin' %}">Signin</a></button>
    </div>
</body>

employee/templates/states.html
<option value="">------</option>
{% for state in states%}
<option value="{{state.pk}}">{{state.name}}</option>
{% endfor %}